def includeme(config):
    config.add_route('registroImportacion', '/registro_importacion')
    config.add_route('registroImportacionGuardar', '/reg_import_guardar')
    config.add_route('ubiVehSeleccionar', '/uv_sel_ubicacion/{idv}')
    config.add_route('ubiVehGuardar', '/uv_guardar_ubicacion/{idv}/{idu}')
    config.add_route('enviarVehReparar', '/enviar_veh_reparar/{idv}')
    config.add_route('filterTalleres', '/tipoRep/{idtrep}/busqtalleres')
    config.add_route('enviarVehRepararGuardar','/enviar_veh_reparar_save')
    config.add_route('costoReparacion','/entrada/costo_reparacion/{id_dce}')
    config.add_route('costoReparacionGuardar','/entrada/costo_reparacion_guardar')
    #CRUD CLIENTES
    config.add_route('clienteLista','/cliente/admon/all')
    config.add_route('clienteCrear','/cliente/admon/create')
    config.add_route('clienteCrearGuardar','/cliente/admon/create_save')
    config.add_route('clienteEditar','/cliente/admon/edit/{id_cliente}')
    config.add_route('clienteEditarGuardar','/cliente/admon/edit_save')
    config.add_route('clienteEliminar','/cliente/admon/delete/{id_cliente}')
    #CRUD MARCAS
    config.add_route('marcaLista','/marca/admon/all')
    config.add_route('marcaCrear','/marca/admon/create')
    config.add_route('marcaCrearGuardar','/marca/admon/create_save')
    config.add_route('marcaEditar','/marca/admon/edit/{id_marca}')
    config.add_route('marcaEditarGuardar','/marca/admon/edit_save')
    config.add_route('marcaEliminar','/marca/admon/delete/{id_marca}')
    #CRUD MODELOS
    config.add_route('modeloLista','/modelo/admon/all')
    config.add_route('modeloCrear','/modelo/admon/create')
    config.add_route('modeloCrearGuardar','/modelo/admon/create_save')
    config.add_route('modeloEditar','/modelo/admon/edit/{id_modelo}')
    config.add_route('modeloEditarGuardar','/modelo/admon/edit_save')
    config.add_route('modeloEliminar','/modelo/admon/delete/{id_modelo}')